[pytest]
addopts = --headed --slowmo 1000 --browser chromium

markers =
    smoke: Smoke testing for critical flows
    regression: Regression testing for deep verification of all features
    
testpaths = Test_Case
